debug: true
languageFile: 'lang.de.yml'
pageSize: 10
topListSize: 5
thxCooldown: 1440
karmaPerThx: 1.0
karmaRegenerationDays: 7
useParticles: true
apiUrlName: 'https://api.mojang.com/user/profiles/{0}/names'
apiUrlUUID: 'https://api.mojang.com/users/profiles/minecraft/{0}'
sql:
  user: 'root'
  password: ''
  database: 'minebench'
  url: 'localhost:3306'
  tables:
    players: 'karma_players'
    transactions: 'karma_transactions'
effects:
  CLOUD:
    delay: 5
  REDSTONE:
    delay: 3
  CRIT:
    delay: 10
  ENDER_SIGNAL:
    delay: 10
  EXPLOSION_NORMAL:
    delay: 10
  EXPLOSION_HUGE:
    delay: 20
  EXPLOSION_LARGE:
    delay: 15
  ENCHANTMENT_TABLE:
    delay: 5
  FIREWORKS_SPARK:
    delay: 10
  FLAME:
    delay: 3
  VILLAGER_HAPPY:
    delay: 5
  HEART:
    delay: 5
  SPELL_INSTANT:
    delay: 5
  SMOKE_LARGE:
    delay: 8
  DRIP_LAVA:
    delay: 5
  LAVA:
    delay: 4
  CRIT_MAGIC:
    delay: 2
  MOBSPAWNER_FLAMES:
    delay: 10
  NONE:
    delay: 0
  NOTE:
    delay: 5
  SMOKE_NORMAL:
    delay: 5
  PORTAL:
    delay: 2
  POTION_BREAK:
    delay: 10
  SPELL_MOB:
    delay: 10
  SPELL_MOB_AMBIENT:
    delay: 10
  SLIME:
    delay: 5
  SMOKE:
    delay: 10
  SNOWBALL:
    delay: 4
  SNOW_SHOVEL:
    delay: 5
  SPELL:
    delay: 5
  WATER_SPLASH:
    delay: 5
  VILLAGER_ANGRY:
    delay: 5
  WATER_DROP:
    delay: 5
  WATER_BUBBLE:
    delay: 5
  SPELL_WITCH:
    delay: 5
levels:
  0: WATER_BUBBLE
  5: VOID_FOG
  25: WATER_DROP
  50: HEART
  75: NOTE
  100: DRIP_LAVA
  125: FLAME
  150: FIREWORKS_SPARK
  175: PORTAL
  200: MOBSPAWNER_FLAMES
  225: REDSTONE
  250: LAVA
  275: SMOKE
  300: CLOUD
  400: ENCHANTMENT_TABLE
  500: SPELL_WITCH
  600: SPELL_MOB