debug: true
languageFile: 'lang.de.yml'
pageSize: 10
topListSize: 5
thxCooldown: 1440
karmaPerThx: 1.0
karmaRegenerationDays: 7
useParticles: true
apiUrlName: 'https://api.mojang.com/user/profiles/{0}/names'
apiUrlUUID: 'https://api.mojang.com/users/profiles/minecraft/{0}'
hideVanished: false
sql:
  user: 'root'
  password: ''
  database: 'minebench'
  url: 'localhost:3306'
  tables:
    players: 'karma_players'
    transactions: 'karma_transactions'
effects:
# levels:
  NONE:
    delay: 0
    karma: 0
  WATER_BUBBLE:
    delay: 5
    karma: 5
  WATER_DROP:
    delay: 5
    karma: 25
  HEART:
    delay: 5
    karma: 50
  NOTE:
    delay: 5
    karma: 75
  DRIP_LAVA:
    delay: 5
    karma: 100
  FLAME:
    delay: 3
    karma: 125
  FIREWORKS_SPARK:
    delay: 10
    karma: 150
  PORTAL:
    delay: 2
    karma: 175
  MOBSPAWNER_FLAMES:
    delay: 10
    karma: 200
  REDSTONE:
    delay: 3
    karma: 225
  LAVA:
    delay: 4
    karma: 250
  SMOKE:
    delay: 10
    karma: 275
  CLOUD:
    delay: 5
    karma: 300
  ENCHANTMENT_TABLE:
    delay: 5
    karma: 400
  SPELL_WITCH:
    delay: 5
    karma: 500
  SPELL_MOB:
    delay: 10
    karma: 600
  CRIT_MAGIC:
    delay: 2
    karma: 900
  SMOKE_NORMAL:
    delay: 5
    karma: 1050
  SMOKE_LARGE:
    delay: 8
    karma: 1250
  VILLAGER_ANGRY:
    delay: 5
    karma: 1500

# non-levels
  CRIT:
    delay: 10
  ENDER_SIGNAL:
    delay: 10
  EXPLOSION_NORMAL:
    delay: 10
  EXPLOSION_HUGE:
    delay: 20
  EXPLOSION_LARGE:
    delay: 15
  VILLAGER_HAPPY:
    delay: 5
  SPELL_INSTANT:
    delay: 5
  POTION_BREAK:
    delay: 10
  SPELL_MOB_AMBIENT:
    delay: 10
  SLIME:
    delay: 5
  SNOWBALL:
    delay: 4
  SNOW_SHOVEL:
    delay: 5
  SPELL:
    delay: 5
  WATER_SPLASH:
    delay: 5