languageFile: 'lang.de.yml'
pageSize: 10
topListSize: 5
karmaPerThx: 1.0
useParticles: true
apiUrlName: 'https://api.mojang.com/user/profiles/{0}/names'
apiUrlUUID: 'https://api.mojang.com/users/profiles/minecraft/{0}'
sql:
  user: 'root'
  password: ''
  database: 'minebench'
  url: 'localhost:3306'
  tables:
    players: 'karma_players'
    transactions: 'karma_transactions'
effects:
  CLOUD:
    delay: 5
  COLOURED_DUST:
    delay: 3
  CRIT:
    delay: 10
  ENDER_SIGNAL:
    delay: 10
  EXPLOSION:
    delay: 10
  EXPLOSION_HUGE:
    delay: 20
  EXPLOSION_LARGE:
    delay: 15
  FLYING_GLYPH:
    delay: 5
  FIREWORKS_SPARK:
    delay: 10
  FLAME:
    delay: 3
  HAPPY_VILLAGER:
    delay: 5
  HEART:
    delay: 5
  INSTANT_SPELL:
    delay: 5
  LARGE_SMOKE:
    delay: 8
  LAVADRIP:
    delay: 5
  LAVA_POP:
    delay: 4
  MAGIC_CRIT:
    delay: 2
  MOBSPAWNER_FLAMES:
    delay: 10
  NONE:
    delay: 0
  NOTE:
    delay: 5
  PARTICLE_SMOKE:
    delay: 5
  PORTAL:
    delay: 2
  POTION_BREAK:
    delay: 10
  POTION_SWIRL:
    delay: 10
  POTION_SWIRL_TRANSPARENT:
    delay: 10
  SLIME:
    delay: 5
  SMALL_SMOKE:
    delay: 5
  SMOKE:
    delay: 10
  SNOWBALL_BREAK:
    delay: 4
  SNOW_SHOVEL:
    delay: 5
  SPELL:
    delay: 5
  SPLASH:
    delay: 5
  VILLAGER_THUNDERCLOUD:
    delay: 5
  VOID_FOG:
    delay: 1
  WATERDRIP:
    delay: 5
  WITCH_MAGIC:
    delay: 5
levels:
  0: NONE
  5: VOID_FOG
  25: WATERDRIP
  50: HEART
  75: NOTE
  100: LAVADRIP
  125: FLAME
  150: FIREWORKS_SPARK
  175: PORTAL
  200: MOBSPAWNER_FLAMES
  225: COLOURED_DUST
  250: LAVA_POP
  275: PARTICLE_SMOKE
  300: CLOUD
  400: FLYING_GLYPH
  500: WITCH_MAGIC
  600: POTION_SWIRL